name: DevSecOps Pipeline
on:
  push:
    branches:
      - main
      - vulnerable-app
      - secure-app
  pull_request:
    branches:
      - main
      - vulnerable-app
      - secure-app
permissions:
  contents: read
  packages: write

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Gitleaks via Go
        run: |
          go install github.com/zricethezav/gitleaks/v8@latest
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
      - name: Run Gitleaks (JSON output)
        run: |
          gitleaks detect --source . --redact --exit-code 0 --report-format json --report-path gitleaks-report.json
      - name: Force create empty report (fallback)
        run: |
          echo '{}' > gitleaks-report.json
      - name: Debug Gitleaks output
        run: | 
          ls -la
          cat gitleaks-report.json || echo "NO FILE"
      - name: Upload Gitleaks artifcat
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-report
          path: gitleaks-report.json
          if-no-files: error
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install pip-audit
        run: pip install pip-audit
      - name: Run Dependency Vulnerability Scan (SCA)
        run: pip-audit || true
      - name: Install Bandit (SAST)
        run: |
          pip install bandit

      - name: Run Bandit Security Scan
        run: |
          bandit -r . -f json -o bandit-report.json || true
      - name: Upload Bandit Report
        uses: actions/upload-artifact@v4
        with:
          name: bandit-report
          path: bandit-report.json
      - name: Run app syntax check
        run: |
          python -m py_compile app.py
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECTKEY }}
            -Dsonar.sources=.
            -Dsonar.exclusions=venv/**,__pycache__/**
            -Dsonar.c.file.suffixes=-
            -Dsonar.objc.file.suffixes=-
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  docker-build:
    runs-on: ubuntu-latest
    needs: build-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}:latest .
      - name: Generate SBOM with Syft
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh
          ./bin/syft scan "ghcr.io/${{ github.repository }}:latest" -o json > sbom.json
      - name: Upload SBOM
        uses: actions/upload-artifact@v4
        with:
          name: sbom-report
          path: sbom-report.json
      - name: Debug SBOM file
        run: |
          ls -la
      - name: Scan Docker image with trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ghcr.io/${{ github.repository }}:latest
          format: json
          output: trivy-report.json
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH,MEDIUM'
      - name: Upload Trivy artifact
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: trivy-report.json
      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Push image to GHCR
        run: docker push ghcr.io/${{ github.repository }}:latest
  deploy:
    needs: [build-test, docker-build]
    runs-on: self-hosted
    steps:
      - name: Deploy locally
        run: |
           docker pull ghcr.io/sarrazouaghi09-star/devsecop-app:latest
           docker stop devsecop-app || true
           docker rm devsecop-app || true
           docker run -d -p 5000:5000 --name devsecop-app ghcr.io/sarrazouaghi09-star/devsecop-app:latest
      - name: Download Bandit report
        uses: actions/download-artifact@v4
        with:
          name: bandit-report
      - name: Download Gitleaks report
        uses: actions/download-artifact@v4
        with:
          name: gitleaks-report
          path: gitleaks-report.json
      - name: Download Trivy Report
        uses: actions/download-artifact@v4
        with:
          name: trivy-report
      - name: Download SBOM report
        uses: actions/download-artifact@v4
        with:
          name: sbom-report
      - name: Upload Bandit
        run: |
          curl -X POST "${{ secrets.DEFECTDOJO_URL }}/api/v2/import-scan/" \
          -H "Authorization: Token ${{ secrets.DEFECTDOJO_API_KEY }}" \
          -F "file=@bandit-report.json" \
          -F "scan_type=Bandit Scan" \
          -F "product_name=airline app" \
          -F "engagement_name=pip" \
          -F "auto_create_context=true"
      - name: Upload Gitleaks to DefectDojo
        run: |
          curl -X POST "http://localhost:8080/api/v2/import-scan/" \
          -H "Authorization: Token ${{ secrets.DEFECTDOJO_API_KEY }}" \
          -F "file=@gitleaks-report.json" \
          -F "scan_type=Gitleaks Scan" \
          -F "product_name=airline app" \
          -F "engagement_name=pip"
      - name: Upload Trivy to DefectDojo
        run: |
          curl -X POST "http://localhost:8080/api/v2/import-scan/" \
          -H "Authorization: Token ${{ secrets.DEFECTDOJO_API_KEY }}" \
          -F "file=@trivy-report.json" \
          -F "scan_type=Trivy Scan" \
          -F "product_name=airline app" \
          -F "engagement_name=pip"
      - name: Upload SBOM to DefectDojo
        run: |
          curl -X POST "http://localhost:8080/api/v2/import-scan/" \
          -H "Authorization: Token ${{ secrets.DEFECTDOJO_API_KEY }}" \
          -F "file=@sbom-report.json" \
          -F "scan_type=CycloneDX Scan" \
          -F "product_name=airline app" \
          -F "engagement_name=pip"
  zap-scan:
    runs-on: ubuntu-latest
    needs: deploy

    steps:
      - name: OWASP ZAP Scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: 'http://192.168.1.171:5000'
      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: report_html.html
